[package]
name = "moq-relay"
description = "Media over QUIC"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/moq"
license = "MIT OR Apache-2.0"

version = "0.9.6"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

[dependencies]

anyhow = { version = "1", features = ["backtrace"] }
axum = { version = "0.8", features = ["tokio", "ws"] }
bytes = "1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
http-body = "1"
hyper-serve = { version = "0.6", features = [
	"tls-rustls",
] } # fork of axum-server
moq-lite = { workspace = true, features = ["serde"] }
moq-native = { workspace = true }
moq-token = { workspace = true }
sd-notify = "0.4"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3", features = ["json", "base64"] }
thiserror = "2"
tokio = { workspace = true, features = ["full"] }
toml = "0.9"
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1"
url = { version = "2", features = ["serde"] }
web-transport-ws = { workspace = true }

[dev-dependencies]
tempfile = "3"
