set shell := ["bash", "-euo", "pipefail", "-c"]

# Run the web server targeting the default relay.
default:
	just serve

# Run the web server targeting the specified relay.
serve url='http://localhost:4443/anon':
	VITE_RELAY_URL="{{url}}" bun run --filter @moq/demo dev
