import { describe, expect, test } from "bun:test";
import { generate } from "./generate.ts";
import { load, loadPublic, sign, verify } from "./key.ts";

// Tests that the JS @moq/token package can load keys generated by the Rust
// moq-token crate and verify tokens signed by Rust, and vice versa.

describe("Rust-generated fixtures", () => {
	// cargo run -p moq-token-cli -- generate --out /tmp/rust-hs256.jwk
	const RUST_HS256_KEY = JSON.stringify({
		alg: "HS256",
		key_ops: ["verify", "sign"],
		kty: "oct",
		k: "jvS2B_SKkvhtObaiKg9n2vq_Iqdus-nVCVVYBWf0BQA",
		kid: "d55b1f13e6bda281",
	});

	// cargo run -p moq-token-cli -- sign --key /tmp/rust-hs256.jwk --root demo --publish alice --subscribe bob
	const RUST_HS256_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJyb290IjoiZGVtbyIsInB1dCI6WyJhbGljZSJdLCJnZXQiOlsiYm9iIl19.eyOkZtTtj_MDkLF4Eu11cygb7B_6DyP-6e0TtwVE4UE";

	// cargo run -p moq-token-cli -- generate --algorithm EdDSA --out /tmp/rust-eddsa-private.jwk --public /tmp/rust-eddsa-public.jwk
	const RUST_EDDSA_PRIVATE_KEY = JSON.stringify({
		alg: "EdDSA",
		key_ops: ["sign", "verify"],
		kty: "OKP",
		crv: "Ed25519",
		x: "S9n3tEG677fSNpa0Ftf46OPBte5y1pTwvm4fPkEw_Z8",
		d: "EhFsuE3CFkJoQpZCT2Wwr6YF7ZwjsaEIgbwO4Uc4b5U",
		kid: "dfab9113ea85dc27",
	});

	const RUST_EDDSA_PUBLIC_KEY = JSON.stringify({
		alg: "EdDSA",
		key_ops: ["verify"],
		kty: "OKP",
		crv: "Ed25519",
		x: "S9n3tEG677fSNpa0Ftf46OPBte5y1pTwvm4fPkEw_Z8",
		kid: "dfab9113ea85dc27",
	});

	// cargo run -p moq-token-cli -- sign --key /tmp/rust-eddsa-private.jwk --root room --publish stream1 --publish stream2 --subscribe feed1
	const RUST_EDDSA_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRmYWI5MTEzZWE4NWRjMjcifQ.eyJyb290Ijoicm9vbSIsInB1dCI6WyJzdHJlYW0xIiwic3RyZWFtMiJdLCJnZXQiOlsiZmVlZDEiXX0.jezhAgTHQHdYkc15CBZP8zPKKJ0z5oVRwON4wPHeQ6xvIhoM5IkCs_4YRCEoG74t99pdVTQrwAMNrlfKm2O6DA";

	test("load Rust HS256 key", () => {
		const key = load(RUST_HS256_KEY);
		expect(key.alg).toBe("HS256");
		expect(key.kid).toBe("d55b1f13e6bda281");
		expect(key.kty).toBe("oct");
	});

	test("verify Rust HS256 token", async () => {
		const key = load(RUST_HS256_KEY);
		const claims = await verify(key, RUST_HS256_TOKEN, "demo");
		expect(claims.root).toBe("demo");
		expect(claims.put).toEqual(["alice"]);
		expect(claims.get).toEqual(["bob"]);
	});

	test("sign with Rust HS256 key and verify roundtrip", async () => {
		const key = load(RUST_HS256_KEY);
		const token = await sign(key, { root: "js-test", put: ["pub1"], get: ["sub1"] });
		const claims = await verify(key, token, "js-test");
		expect(claims.root).toBe("js-test");
		expect(claims.put).toEqual(["pub1"]);
		expect(claims.get).toEqual(["sub1"]);
	});

	test("load Rust EdDSA keys", () => {
		const privateKey = load(RUST_EDDSA_PRIVATE_KEY);
		expect(privateKey.alg).toBe("EdDSA");
		expect(privateKey.kty).toBe("OKP");

		const publicKey = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		expect(publicKey.alg).toBe("EdDSA");
		expect(publicKey.kty).toBe("OKP");
	});

	test("sign with Rust EdDSA private key and verify with public key", async () => {
		const privateKey = load(RUST_EDDSA_PRIVATE_KEY);
		const publicKey = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		const token = await sign(privateKey, { root: "js-eddsa", put: ["test"] });
		const claims = await verify(publicKey, token, "js-eddsa");
		expect(claims.root).toBe("js-eddsa");
		expect(claims.put).toEqual(["test"]);
	});

	test("verify Rust EdDSA token with public key", async () => {
		const key = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		const claims = await verify(key, RUST_EDDSA_TOKEN, "room");
		expect(claims.root).toBe("room");
		expect(claims.put).toEqual(["stream1", "stream2"]);
		expect(claims.get).toEqual(["feed1"]);
	});
});

describe("wrong key rejects token", () => {
	// cargo run -p moq-token-cli -- generate --out /tmp/rust-hs256.jwk
	const RUST_HS256_KEY = JSON.stringify({
		alg: "HS256",
		key_ops: ["verify", "sign"],
		kty: "oct",
		k: "jvS2B_SKkvhtObaiKg9n2vq_Iqdus-nVCVVYBWf0BQA",
		kid: "d55b1f13e6bda281",
	});

	// cargo run -p moq-token-cli -- sign --key /tmp/rust-hs256.jwk --root demo --publish alice --subscribe bob
	const RUST_HS256_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJyb290IjoiZGVtbyIsInB1dCI6WyJhbGljZSJdLCJnZXQiOlsiYm9iIl19.eyOkZtTtj_MDkLF4Eu11cygb7B_6DyP-6e0TtwVE4UE";

	test("different HS256 key rejects Rust token", async () => {
		const wrongKey = await generate("HS256");
		await expect(verify(wrongKey, RUST_HS256_TOKEN, "demo")).rejects.toThrow();
	});

	test("wrong root path rejects token", async () => {
		const key = load(RUST_HS256_KEY);
		await expect(verify(key, RUST_HS256_TOKEN, "wrong-root")).rejects.toThrow();
	});

	test("tampered token is rejected", async () => {
		const key = load(RUST_HS256_KEY);
		// Flip a character in the signature
		const tampered = RUST_HS256_TOKEN.slice(0, -1) + (RUST_HS256_TOKEN.at(-1) === "A" ? "B" : "A");
		await expect(verify(key, tampered, "demo")).rejects.toThrow();
	});

	test("EdDSA token rejected by HS256 key", async () => {
		const key = load(RUST_HS256_KEY);
		// cargo run -p moq-token-cli -- sign --key /tmp/rust-eddsa-private.jwk --root room --publish stream1 --publish stream2 --subscribe feed1
		const eddsaToken =
			"eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRmYWI5MTEzZWE4NWRjMjcifQ.eyJyb290Ijoicm9vbSIsInB1dCI6WyJzdHJlYW0xIiwic3RyZWFtMiJdLCJnZXQiOlsiZmVlZDEiXX0.jezhAgTHQHdYkc15CBZP8zPKKJ0z5oVRwON4wPHeQ6xvIhoM5IkCs_4YRCEoG74t99pdVTQrwAMNrlfKm2O6DA";
		await expect(verify(key, eddsaToken, "room")).rejects.toThrow();
	});

	test("garbage token is rejected", async () => {
		const key = load(RUST_HS256_KEY);
		await expect(verify(key, "not-a-jwt", "demo")).rejects.toThrow();
	});
});
