// swift-tools-version:5.9
// Local-development manifest. swift/scripts/check.sh builds a single-slice
// MoqFFI.xcframework next to this file so the path-based binaryTarget below
// resolves locally without a network fetch.
//
// The released form (URL + checksum) is generated by swift/scripts/package.sh
// from Package.swift.template at release time. Edit the template, not this
// file, when changing the released manifest.

import PackageDescription

let package = Package(
    name: "Moq",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [.library(name: "Moq", targets: ["Moq"])],
    targets: [
        .target(name: "Moq", dependencies: ["MoqFFI"], path: "Sources/Moq"),
        .target(name: "MoqFFI", dependencies: ["MoqFFIBinary"], path: "Sources/MoqFFI"),
        .binaryTarget(name: "MoqFFIBinary", path: "MoqFFI.xcframework"),
        .testTarget(name: "MoqTests", dependencies: ["Moq"], path: "Tests/MoqTests"),
    ]
)
