set fallback

# Subscribe to a broadcast using GStreamer and render to the screen.
gst name url='http://localhost:4443/anon' *args:
	cargo build -p moq-gst

	GST_PLUGIN_PATH_1_0="${PWD}/../../target/debug${GST_PLUGIN_PATH_1_0:+:$GST_PLUGIN_PATH_1_0}" \
	gst-launch-1.0 -v -e moqsrc url="{{url}}" broadcast="{{name}}" {{args}} \
		! decodebin3 ! videoconvert ! autovideosink
